### ISSUE TITLE
Forces CUDA Device 0

### ISSUE THREAD

**Issue by drewnutt** [gnina/libmolgrid#43]
The following occured when using molgrid with pytorch. When I set all of my pytorch tensors to `cuda:1` I get an error when running `gridmaker.forward`
> gmaker.forward(batch_1, input_tensor_1,random_translation=2.0, random_rotation=True)
> RuntimeError: CUDA Error: invalid argument

`input_tensor_1` was initialized to device `cuda:1`

**Comment by dkoes** [comment]
With 0.5.1 more informative error messages are generated if a torch tensor isn't on the current GPU device and helper functions (`molgrid.set_gpu_device` and `molgrid.get_gpu_device`) are now available for changing the current GPU.

I think it is best practice to make the programmer explicitly decide what GPU things are on, so calling `molgrid.set_gpu_device` is going to be the solution rather than implicitly changing GPU devices to match the tensor.

**Comment by RMeli** [comment]
Are `molgrid.set_gpu_device` and `molgrid.get_gpu_device` documented anywhere? I think it would be beneficial to add  `molgrid.set_gpu_device`  to the tutorial (and the documentation if not already there, I was unable to find them).

**Comment by dkoes** [comment]
I needed to add these methods to the sphinx rst file for them to show up in the documentation.  I've pushed the change.  I'd gladly accept a pull request for a more comprehensive getting started tutorial (it's on the todo list, but happy for someone else to do it)...

**Comment by RMeli** [comment]
Thanks, it will be very useful to have these functions documented.

I almost finished a [PyTorch-based implementation of the GNINA scoring function](https://github.com/RMeli/gnina-torch/tree/affinity) (to be extended for flexible docking) so maybe a subset of that could be used as a starting point for a more comprehensive tutorial? (However I used PyTorch-Ignite quite heavily, which might obfuscate `molgrid` concepts...)

I've been wanting to put my own notes about GNINA and `molgrid` into some sort of "user guide" but I haven't yet had time to think more concretely about it either.
