### ISSUE TITLE
Memory leak using cache_structs

### ISSUE THREAD

**Issue by jscant** [gnina/libmolgrid#46]
I noticed a lot of my jobs using Tensorflow with molgrid were getting OOM errors at about 6 hours runtime. I tracked the memory consumed by the python process:

![MicrosoftTeams-image](https://user-images.githubusercontent.com/39645092/92587414-25636880-f287-11ea-8cd3-f1b7cdee7eea.png)

This equates to about 3.5 gb/hour and my models often take 24+ hours to run, hence the OOMs.

I isolated the leak to one line of code:

`batch = e.next_batch(batch_size)`

where `e` is an ExampleProvider object. After rooting around in the docs, I found the 'cache_structs' option to be suspect, so I constructed my ExampleProvider with cache_structs=False, and the leak disappeared:

![memory](https://user-images.githubusercontent.com/39645092/92587611-6a879a80-f287-11ea-83d1-0fc5e43a2533.png)

I do not know if this is a leak in the strictest sense or intended behaviour. Perhaps an (configurable?) ceiling on the size of the cache would be useful?

**Comment by dkoes** [comment]
With cache_mols enabled, your entire dataset will be loaded into memory (after processing - so just the xyz coordinates and type information).  If your dataset doesn't fit in memory, you will run out.  What you should see is a steady increase in memory usage until you have done one complete epoch at which point it levels off.  

If your dataset isn't very large and/or you are seeing increased memory usage after performing a complete epoch, we will investigate, but otherwise it is the expected behavior.

If you aren't using vector typing, you can use the create_caches2.py script (https://github.com/gnina/scripts/blob/master/create_caches2.py) to assemble your dataset into one very efficient memory-mappable file.  Memory mapping let's you benefit from in-memory data without having to worry about out-of-memory errors (and especially valuable when running multiple jobs on the same node).

**Comment by jscant** [comment]
The models I'm using are on the edge of what's possible to store in the memory that I have available, so the 23gb dataset on top of that is indeed giving me OOM problems. I suppose this can be closed, perhaps adding something to the docs warning about large datasets and the default constructor (cache_structs=True) would be useful.

Thanks for the prompt response.
